### ISSUE TITLE
Refactor JS code to be ES5 compliant

### ISSUE THREAD

**Issue by andersonmadeira** [andersonmadeira/clock#17]
Replace all es6+ code to ES5 equivalent code, just so the code runs in any ES5 compliant browser without the need to use a mobile bundler.

**Comment by sorbx64** [comment]
Hi, I would like to use babel to transpile the es6 code to es5(with semicolons), keeping code formatting the same.

**Comment by amadeirado** [comment]
Oh hi @saurabh-33, thank you for your interest in contributing to this project.

I started this project with the intent for it to be simple for new web developers, just so it remains as an example that you dont't need fancy stuff to be a web developer and to focus on the basic foundation principles for web development.

I originally created a issue for that [here](https://github.com/andersonmadeira/clock/issues/9#issuecomment-724748212), but I closed it in with that thought in mind.

Maybe adding a basic webpack and babel config would not add that much complexity to the project, not more than replacing all those features with ES5 code. 

If you wish, you can close this issue and you can continue working on [that issue](https://github.com/andersonmadeira/clock/issues/9#issuecomment-724748212)

Thanks

**Comment by amadeirado** [comment]
As previously discussed, we'll try to keep the format and add that compatibility by setting up some webpack and babel configuration as part of #9
