### ISSUE TITLE
Setup GitHub Action to deploy to GitHub pages after PR is merged into master

### ISSUE THREAD

**Issue by andersonmadeira** [andersonmadeira/clock#23]

**Comment by Simhanischal** [comment]
Hi Anderson, as far as I know, when the code is merged to master, the latest code change is automatically deployed to Github pages. Correct me if I am wrong.

**Comment by amadeirado** [comment]
Oh, you're kinda right, my bad. 
Turns out we need to setup a default branch to be used for github pages, that could be master as you said. 
Therefore there's no real purpose for this issue.

**Comment by Simhanischal** [comment]
Yes exactly. I guess Issue #15 can also be closed after setting up the Github pages which is also a simple thing to do.
